export const SOFTWARE_LIST = [
  '3D Viewer',
  'Adaptive Vision Studio',
  'AMD Radeon Software',
  'Anaconda3 2023.09',
  'Arduino IDE',
  'Blender',
  'Calculator',
  'Camera',
  'Clock',
  'Copilot',
  'Docker Desktop',
  'Dropbox',
  'Feedback Hub',
  'FlexSim 2019',
  'Foxit PDF Reader',
  'Git',
  'Google Chrome',
  'i3ALLSYNC 4.0',
  'IBM ILOG CPLEX Optimization Studio',
  'Ink Handwriting',
  'Intel C++ Redistributable x64',
  'Intel C++ Redistributable x86',
  'Intel Graphics Command Center',
  'Intel Optane Memory',
  'IntelliJ IDEA Community',
  'Java SE Development Kit v1',
  'Java SE Development Kit v2',
  'Mail and Calendar',
  'Maps',
  'MatrikonOPC Analyzer',
  'MatrikonOPC Explorer',
  'MatrikonOPC Server',
  'Media Player',
  'Microsoft .NET Framework',
  'Microsoft 365 Copilot',
  'Microsoft Bing',
  'Microsoft Clipchamp',
  'Microsoft Edge',
  'Microsoft Edge for Gaming',
  'Microsoft Help Viewer',
  'Microsoft ODBC Driver',
  'Microsoft OLE DB Driver',
  'Microsoft OneDrive',
  'Microsoft SQL Server',
  'Microsoft System CLR Types v1',
  'Microsoft System CLR Types v2',
  'Microsoft Teams',
  'Microsoft Teams Meeting Add-in',
  'Microsoft To Do',
  'Microsoft Update Health Tools',
  'Microsoft Visual C++ Redistributable v1',
  'Microsoft Visual C++ Redistributable v2',
  'Microsoft Visual C++ Redistributable v3',
  'Microsoft Visual C++ Redistributable v4',
  'Microsoft Visual Studio (IDE)',
  'Microsoft Visual Studio Build Tools',
  'Microsoft Visual Studio Shell',
  'Microsoft Windows Desktop Runtime',
  'Microsoft_VC90_All_x64',
  'Microsoft_VC90_All_x86',
  'Minitab 19',
  "Module d'experience",
  'Module linguistique',
  'Movies & TV',
  'News',
  'Node.js',
  'Notepad',
  'OBS Studio',
  'Ollama 0.24.0',
  'OneNote for Windows',
  'OPC Core Components',
  'Oracle VirtualBox 7.1.8',
  'Outlook',
  'Paint',
  'Paint 3D',
  'People',
  'Photos',
  'Power Automate',
  'Python 3.12.1 (64-bit)',
  'Python Launcher',
  'Quick Assist',
  'RapidMiner Studio',
  'Raspberry Pi Imager',
  'Realtek Audio Console',
  'Remote Desktop Connection',
  'Skype',
  'Snipping Tool',
  'Solitaire & Casual Games',
  'Sound Recorder',
  'Speech Pack - French',
  'Spotify',
  'Start Experiences App',
  'Sticky Notes',
  'Tableau Public 2022.1',
  'Tanagra 1.4',
  'Terminal',
  'Ubuntu on Windows',
  'Unity',
  'Update for x64-based Systems',
  'Veyon',
  'Visual Studio Community',
  'VLC media player',
  'Weather',
  'Web Media Extensions',
  'Weka 3.9.6',
  'WhatsApp',
  'Windows App Runtime',
  'Windows SDK AddOn',
  'Windows Software Development Kit',
  'Windows Subsystem for Linux',
  'WinRAR 6.24 (64-bit)',
  'Xbox',
  'Xbox Console Companion',
  'Xbox Live',
] as const satisfies readonly string[]
